### ISSUE TITLE
Make it easier to create personal mirrors of the schemas

### ISSUE THREAD

**Issue by kellerb** [irods/irods_schema_configuration#19]

**Comment by vladimir-mencl-eresearch** [comment]
Hi Ben,

Thanks - good to see this would get taken care of.

Being able to make a local copy sounds good!

Just note that at the moment, `irodsctl.pl` insists on having an `https` URL for the schema location:

```
    if ( $SCHEMA_VALIDATION_BASE_URI =~ /^https?:\/\// )
```

... so there are some changes in scripts that would be needed to support `file://` URLs.  (I think the python script doing the json schema validation was rejecting `file://` URLs as well...)

Cheers,
Vlad

**Comment by trel** [comment]
The `?` makes the `s` optional - `http` should be okay.  It currently does require a dereferenceable URI though, as that is how the recursive calls get handled.  I'm not sure whether `file://` URIs will suffice.

**Comment by kellerb** [comment]
Hey @vladimir-mencl-eresearch, iRODS proper has been adjusted to work with `file://` URL schemes when validating configuration files, and I have rearranged this repo and created `deploy_schemas_locally.py` to make it easy to create local copies of the schemas.

The changes to iRODS will be included in 4.1.4.
