### ISSUE TITLE
No v2 schemas 

### ISSUE THREAD

**Issue by kript** [irods/irods_schema_configuration#23]
On a system which has been upgraded from 3.3.1 run-in-place to 4.1.7 packaged on Ubuntu using Oracle, I get 

```
No such file or directory: '/etc/irods/irods_schemas/v2/service_account_environment.json'
```

Presumably this is due to the upgrade using a previous version of the schemas?

Full test is below;

```
irods@icat:~$ git clone https://github.com/irods/irods_schema_configuration.git
Cloning into 'irods_schema_configuration'...
remote: Counting objects: 354, done.
irods@icat:~$ mkdir /etc/irods/irods_schemas
irods@icat:~$ cd irods_schema_configuration/
irods@icat:~/irods_schema_configuration$ python deploy_schemas_locally.py --output_directory_base /etc/irods/irods_schemas/
vagrant@icat:~/irods_schema_configuration$ sudo /etc/init.d/irods stop
Stopping iRODS server...

irods@icat:/etc/irods$ diff server_config.json server_config.json.b4.1.1.11
38c38
<     "schema_validation_base_uri": "file:///etc/irods/irods_schemas", 

---
>     "schema_validation_base_uri": "https://schemas.irods.org/configuration", 
52c52
< }

---
> }
\ No newline at end of file

vagrant@icat:~/irods_schema_configuration$ sudo /etc/init.d/irods start
]Starting iRODS server...
Confirming catalog_schema_version... Success
ERROR: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]
     : against [file:///etc/irods/irods_schemas/v2/service_account_environment.json]
  IOError: [Errno 2] No such file or directory: '/etc/irods/irods_schemas/v2/service_account_environment.json'
Preflight Check problem:
   JSON Configuration Validation failed.
```

**Comment by trel** [comment]
The default branch for a new clone is `v3`.  You need to checkout `v2`.

Please try this:

``` bash
git clone https://github.com/irods/irods_schema_configuration.git
cd irods_schema_configuration
git checkout v2
python deploy_schemas_locally.py --output_directory_base /etc/irods/irods_schemas/
```

**Comment by kellerb** [comment]
I have updated the `README.md` to address this.

**Comment by kript** [comment]
Thanks @trel - thats worked.
@kellerb  - thank you! Could I ask you to add something so that people know which version to checkout - the README implies v3 is the production one, where I believe it's actually the development branch? It's not clear which version one should use and why, if you see what I mean!

**Comment by kellerb** [comment]
Updated `README.md` to tell how to determine an iRODS installation's schema version.

> To determine which version of the schemas is used by an iRODS installation, check the `configuration_schema_version` entry of `/var/lib/irods/VERSION.json`.

Overly specific explanation of iRODS schemas below:

Each full version of iRODS (e.g. 4.1.6 vs. 4.1.7) could use a different schema version. It just so happens that all the iRODS 4.1.x releases have used schema version 2 so far (and will probably continue to do so) and that iRODS 4.2 required a change to the schema, which necessitated the creation of schema version 3.

Note that the contents of a schema version are not locked until the release of a product that depends on them, meaning that schema version 3 is currently in flux (no released software uses it) and will most likely be frozen with the release of iRODS 4.2.0. Schema version 3 could be frozen sooner if it was determined that another 4.1 point release required a schema change. At that point, if 4.2 was determined to require more changes than those in the hypothetical point release, schema version 4 would be created and iRODS 4.2 would be pointed at it.
